version: "3"
services:
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init_conf.sh:/docker-entrypoint-initdb.d/init_conf.sh
  back:
    image: python:3.10-slim-buster
    restart: always
    depends_on:
      - db
    working_dir: /app
    expose:
      - "800"
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      POSTGRES_HOST: db
    volumes:
      - .:/app
    command: bash -c "apt-get update
      && apt-get install -y curl
      && curl -sSL https://install.python-poetry.org | python3 -
      && export PATH=/root/.local/bin:$PATH
      && poetry install
      && poetry run python server.py"